name: Update gist with WakaTime stats
on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: z-------------/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: cc8311bc01aa0abde4f69dcacec4cfaf
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
