name: Update gist with WakaTime stats
on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install dependencies
        run: npm ci
      - name: Update gist
        run: node index.js
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 59191c40d060eb65a2bc1d0386fb6668
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
